### ISSUE TITLE
Bug: last entry  in dataset counter is 0

### ISSUE THREAD

**Issue by Aksei** [mad-lab-fau/NilsPodLib#15]
Error occurs when trying to align a SynchSession: `session = session.align_to_syncregion()` .
Error message: `ValueError: The start values need to be smaller then their respective end values!`. 

Underlying problem: The last entry of one of the dataset's counter arrays is 0.

Work around: Skip the last ten samples.
```
    try:
        session = session.align_to_syncregion()
    except ValueError as e:
        print("Sync Warning: % s" % e, file=sys.stderr)
        session = session.cut(stop=-10)
        session = session.align_to_syncregion() 
```

**Comment by richrobe** [comment]
@AKuederle

**Comment by AKuederle** [comment]
starting from version 3.5, we provide a better error message for this issue and explain the workaround as part of the error.

We still expect you todo the workaroud manually (I want that you are aware that you are handling a bug, and that this is not normal behavior).

However, the workaround detailed here needs to be changed slightly, as the Exception type is changed.

```python
from nilspodlib.exceptions import SynchronisationError

try:
    session = session.align_to_syncregion()
except SynchronisationError as e:
    print("Sync Warning: % s" % e, file=sys.stderr)
    session = session.cut(stop=-10)
    session = session.align_to_syncregion() 
```
